### ISSUE TITLE
MessegDecodingError

### ISSUE THREAD

**Issue by sevweb** [lovetodream/oracle-nio#30]
I try to connect to an remote server in get this error:
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: OracleSQLError(code: connectionError, underlying: OracleNIO.OracleMessageDecodingError(packetID: 2, payload: "00 20 00 00 02 00 00 00 01 3a 04 01 20 00 20 00 01 00 00 00 00 20 c5 00 00 00 00 00 00 00 00 00", description: "Expected at least \'4\' remaining bytes. But found 0.", file: "OracleNIO/OracleBackendMessage+Accept.swift", line: 32))

**Comment by lovetodream** [comment]
Which Oracle Database version are you connecting to?

**Comment by sevweb** [comment]
11.2.0 Express

**Comment by lovetodream** [comment]
Oracle 11.2 is not and will not be supported, I'm afraid. The driver only supports Oracle 12.1 and newer. 
The error is misleading though and will be improved with #32.
