### ISSUE TITLE
Need "cursor.description"  or something similar to get the column names.

### ISSUE THREAD

**Issue by bhregmi** [lovetodream/oracle-nio#31]
Need some method to display column names from output of "sys_refcursor" ( Some time the stored proc will generate dynamic column names , so that need to be taken into account too).

**Comment by lovetodream** [comment]
I've added the column names as part of [`Cursor.columns`](https://github.com/lovetodream/oracle-nio/blob/8066aa3d08a977ece671268d89d4d7b214cdad92/Sources/OracleNIO/Data/Cursor.swift#L22) in the branch `feature/expose-column-metadata`, can you try it out and give me feedback if the column name's are enough?

You can test it by setting the dependency on oracle-nio to the following:
```swift
.package(url: "https://github.com/lovetodream/oracle-nio.git", branch: "feature/expose-column-metadata")
```

I'd like to avoid making unnecessary details public prematurely as it makes it harder to change internals in the future. That's the reason why I decided to only make the column names public for now.

I'll merge it once you've given me positive feedback :)

**Comment by bhregmi** [comment]
Yes it worked as intended:

    do {
        let cursor = try cursorRef.decode(of: Cursor.self)
        let stream = try await cursor.execute(on: connection)
        
        // Print column headers
        for column in cursor.columns {
            let columnName = column.name
            print("\(columnName)\t", terminator: "")
        }
        print() // Print new line after printing column headers
        
        // Iterate through rows and print data
        for try await row in stream.decode((String, String, String, String,String,String,Double).self) {
            let column0 = row.0
            let column1 = row.1
            let column2 = row.2
            let column3 = row.3
            let column4 = row.4
            let column5 = row.5
            let column6 = row.6
            
            // Print row values
            print("\(column0)\t\(column1)\t\(column2)\t\(column3)\t\(column4)\t\(column5)\t")
        }
        
    } catch {
        print("Error decoding : \(error)")
    }
