### ISSUE TITLE
Not sure how to decode unicode

### ISSUE THREAD

**Issue by huyphams** [lovetodream/oracle-nio#41]
The result of
```
SELECT 'ьми' as col from dual
```
All are question marks, maybe I am doing something wrong?

**Comment by huyphams** [comment]
I just simplified the example.

**Comment by lovetodream** [comment]
Hm, I cannot reproduce the issue, what's the charset you're using?

**Comment by huyphams** [comment]
I'm using the default setup connect as the example and the run the select above, the result are question marks. How do we set the charset?

**Comment by lovetodream** [comment]
Sorry, my question was a bit unclear. I meant the database charsets, you can check it with this query:
```
SELECT *
  FROM v$nls_parameters
 WHERE parameter LIKE '%CHARACTERSET'
```

**Comment by cjbj** [comment]
What does your failing query `SELECT 'ьми' as col from dual` show in SQL*Plus?

**Comment by huyphams** [comment]
Solved by using Data decode.
