### ISSUE TITLE
Documentation issue: instead of connection.execute

### ISSUE THREAD

**Issue by kicsipixel** [lovetodream/oracle-nio#55]
In the documentation and snippets it is written the example this way:

`let rows = try await connection.execute("SELECT id, username, birthday FROM users", logger: logger)`

But `connection` is not `public` anymore, so it should be `query`. 
Small thing only.

**Comment by lovetodream** [comment]
Actually connection is an instance of `OracleConnection`, which should be public. Maybe I'm misunderstanding what you mean, can you link the problematic snippets?

**Comment by lovetodream** [comment]
Ah yes, the last alpha release doesn't include the change to execute yet, so documentation is "to new". The change to execute is on main though. I should tag a new alpha release...
https://github.com/lovetodream/oracle-nio/blob/c4da4c16aefdd39792c610df6bb5225d50df044d/Sources/OracleNIO/Connection/OracleConnection.swift#L443

**Comment by lovetodream** [comment]
Docs are now up to date and a new release is tagged
