### ISSUE TITLE
Crash when I load 4 columns but not 3

### ISSUE THREAD

**Issue by fcobia** [lovetodream/oracle-nio#6]
I am querying a table that has 4 columns. If I try to get all 4 columns it crashes, but if I only query any 3 of the columns it works perfectly.

It crashes on 4 because when it gets to line 728 in moreDataReceived in ExtendedQueryStateMachine `messages` has two values the first is of type `.bitVector`, but the second is `.dataTypes` which hits the `default` case and crashes. When I only query 3 columns `messages` only contains a single item of type `.bitVector`.

Below is a section of the crashing code. Not that `ID` and `WEIGHT` are `NUMBER(10)` and the other columns are `VARCHAR`.
```
		let rows = try await conn.query(
			"SELECT ID, NAME, DISPLAYNAME, WEIGHT FROM MYTABLE",
			logger: logger
		).collect()
		
		let rowValues = try XCTUnwrap(try rows.first?.decode((Int, String, String, Int).self))
```

The following code works and you can swap the `ID` and the `WEIGHT` columns.
```
		let rows = try await conn.query(
			"SELECT ID, NAME, DISPLAYNAME FROM MYTABLE",
			logger: logger
		).collect()
		
		let rowValues = try XCTUnwrap(try rows.first?.decode((Int, String, String).self))
```

**Comment by fcobia** [comment]
There are only 4 rows in the table. I forgot to mention I am using `OracleConnection.Configuration.disableOOB` if that makes a difference. 

I will try to post the Oracle code for creating the table and populating it when I am in front of my computer later.

**Comment by lovetodream** [comment]
> I will try to post the Oracle code for creating the table and populating it when I am in front of my computer later.

That would be great. OOB shouldn't make a difference :)

**Comment by lovetodream** [comment]
I was able to reproduce the issue with multiple rows. It should be fixed now, let me know if it works for you too

**Comment by fcobia** [comment]
That fixed the issue. Thank you.

I am not sure how much time I have, but this is a project that I have wanted to see for several years now. I have no idea how the Oracle protocol works. Do you have any documentation about how the protocol works or how I can get started understanding your code and then maybe I can help contribute.

**Comment by lovetodream** [comment]
The protocol isn't documented publicly. At the time I started work on this driver, I contacted Oracle and they told me they're working on "thin" drivers (At that time all open source drivers where backed by OCI or ODPI, which are proprietary and these "thin" drivers won't need that, same as this swift-driver). Shortly after, they've released "thin mode" within the [python-oracledb](https://github.com/oracle/python-oracledb) driver. I've used that as the main reference, alongside asking Oracle directly when things have been unclear. There is also a "thin mode" in the [node-oracledb](https://github.com/oracle/node-oracledb) now.

If you want to contribute, you should start by familiarizing yourself with [swift-nio](https://github.com/apple/swift-nio) in general, if that isn't the case already. The best way to start understanding the code is probably by looking at [`OracleChannelHandler`](https://github.com/lovetodream/oracle-nio/blob/main/Sources/OracleNIO/OracleChannelHandler.swift) and then go from there. (a good thing is to add breakpoints on stuff that interests you and see when they are hit and so on)

BTW your issues are a great contribution already, currently there aren't many features left to add. So finding bugs and edge cases is my main focus before publishing a first release.
The only feature I'd like to add before that first release is JSON support.
