### ISSUE TITLE
NIOCore.ChannelError.connectTimeout

### ISSUE THREAD

**Issue by Tommynocker** [lovetodream/oracle-nio#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OracleNIO version

Main

### Database version

19C

### Operating system and version

macOS 15.0

### Swift Version

.package(url: "https://github.com/lovetodream/oracle-nio.git", branch: "main"),

### Describe the bug

In the new macOS the come a connection Timeout
NIOCore.ChannelError.connectTimeout(NIOCore.TimeAmount(nanoseconds: 10000000000)) 

### Steps To Reproduce

 let logger = Logger(label: "oracle-logger")
        
        let config = OracleConnection.Configuration(
            host: "xx",
            port: x,
            service: .serviceName("Test"),
            username: "x",
            password: "x"
        )
        
        let connection = try await OracleConnection.connect(
          configuration: config,
          id: 99,
          logger: logger
        )
        
>>>> here come the timeout

### Outcome

NIOCore.ChannelError.connectTimeout(NIOCore.TimeAmount(nanoseconds: 10000000000))

**Comment by lovetodream** [comment]
Did it work with older macOS versions for you?
Are you connecting to the db in a iOS, macOS, etc. or a Server app?

**Comment by Tommynocker** [comment]
yes it works with older Macos version. But now it works, I disabled the firewall in settings

**Comment by lovetodream** [comment]
Ah, that's great to hear, thanks for letting me know!

**Comment by Tommynocker** [comment]
can you say me how I map a OracleRow to a struct?

**Comment by lovetodream** [comment]
This is not possible right now, but it might soon be, have a look at this #60 

For now you need to do something like this:
```swift
struct User {
  var id: Int
  var name: String
  var age: Int
}
let stream = try await connection.query("SELECT id, name, age FROM users")
var users: [User] = []
for try await (id, name, age) in stream.decode((Int, String, Int).self) {
  users.append(.init(id: id, name: name, age: age))
}
print(users)
```

**Comment by Tommynocker** [comment]
thanks i implemented this , but how i implement this if I have a lot of columns.? or i work with select *  
Is there a way to make it more comfortable?

**Comment by lovetodream** [comment]
At the moment, this is the only way, even with a lot of columns. I know it is not ideal, I have noticed it myself when working with 20+ columns in my select statements. This will get a lot easier with #60.

I would advice you to never use SELECT *, even if you want to select every column, it is still slower than typing out every column. Not to mention the problems that can happen when you add more columns later and forget about a SELECT * somewhere. This advice generally applies to all relational databases and all database drivers in every language.
