### ISSUE TITLE
Repository cannot be cloned by SPM

### ISSUE THREAD

**Issue by Joshaphat** [lovetodream/oracle-nio#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

when i used "getting started" method to integration this on my project, terminal throws exception 

> error: Failed to clone repository https://github.com/lovetodream/oracle-nio.git:
>     Cloning into bare repository '/Users/zhaizhijie/Desktop/TestNavicat/.build/repositories/oracle-nio-f7187c33'...
>     fatal: unable to access 'https://github.com/lovetodream/oracle-nio.git/': Recv failure: Connection reset by peer

Is my Package.swift

let package = Package(
    name: "TestNavicat",
    platforms: [.macOS(.v11), .iOS(.v12)],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "TestNavicat",
            targets: ["TestNavicat"]),
    ], dependencies: [
        .package(url: "https://github.com/lovetodream/oracle-nio.git", from: "1.0.0-alpha"),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "TestNavicat"),
        .testTarget(
            name: "TestNavicatTests",
            dependencies: [.product(name: "OracleNIO", package: "oracle-nio"),]),
        
    ]
)

**Comment by lovetodream** [comment]
Are you using Xcode, if yes what's the version?

**Comment by Joshaphat** [comment]
Version 15.4

**Comment by kicsipixel** [comment]
Do other packages work? Hasn't  your SSH key  expired?

**Comment by lovetodream** [comment]
You can also try restarting Xcode (does wonders sometimes) if you didn't do it already. Or use the command line (swift package resolve, swift package update, etc. in the folder of your Package.swift file)

**Comment by lovetodream** [comment]
Closed due to off topic and no response
