### ISSUE TITLE
OracleNIO/ByteBuffer+ReadOracleBytes.swift:92: Fatal error

### ISSUE THREAD

**Issue by Tommynocker** [lovetodream/oracle-nio#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OracleNIO version

Main

### Database version

12.2

### Operating system and version

macOS 15

### Swift Version

swift 6

### Describe the bug

We have trouble querying a view from our database. The view contains some specific oracle functions and some of the sources for this view is also another view. So it's a cascaded system, which caused no problems when queried in other DBMS.

When using the OracleNIO component via Swift and programmatically loop through the results, we receive the following Exception "OracleNIO/ByteBuffer+ReadOracleBytes.swift:92: Fatal error". We suspect, that because of the complex view-structure there is a synchronization problem. Because when querying a simple view but with over 1mil rows, the data is collected correctly.

Do you have any suggestions what we could try? Is there a parameter or option we can/should set in OracleNIO when establishing the database connection?

**Comment by lovetodream** [comment]
Are you sure you're on the latest commit on main? Alternatively use 1.0.0-beta.3. The issue you're facing should've been fixed with #75 
Let me know if it works after updating.

**Comment by Tommynocker** [comment]
yes latest main, with 1.0.0-beta.3 it works

**Comment by lovetodream** [comment]
Glad to hear that, the latest commit on main is the same as 1.0.0-beta.3, so it works too. Maybe SPM didn't update correctly. Anyway this is fixed, thanks for reporting!
