### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by fcobia** [lovetodream/oracle-nio#9]
I am trying to do some inserts against an Oracle 23c free database instance. I have run into a problem that my inserts are not committed. I was able to get my code to work by setting the query option autoCommit to true. However, this is a problem because I have build a sql-kit adaptor above it and it might be a pain to be able to set auto commit on an individual transaction basis. 

Is there a way to set autoCommit globally for the connection?

I actually would like to do manual commits, but when I do that I get a OracleSQLError.malformedQuery exception because ExtendedQueryContext does not recognize commit. 

Do you have some advice?

**Comment by lovetodream** [comment]
It's definitely possible to add a feature for connection wide autocommits to the driver.
I'll have a look at it next week.

How do you build your queries with commit? Can you give me an example, so I'm able to have a look at that too?

**Comment by fcobia** [comment]
I just execute a statement using raw and then try to use raw to do a commit. This is actually sql-kit code running on top of Oracle NIO

try db.insert(into: tableName).model(testData)
try await db.raw("COMMIT").run()

**Comment by fcobia** [comment]
Also, the flip side is that there doesn't seem to be a way to rollback

**Comment by fcobia** [comment]
I made a change that seems to work. I modified the switch statement (see below) in ExtendedQueryContext to add "COMMIT" as a .dlm and it seems to work. Rollback works in that I do not get an error, but it doesn't seem to work.

        switch sqlKeyword {
        case "DECLARE", "BEGIN", "CALL":
            return .plsql(promise)
        case "SELECT", "WITH":
            return .query(promise)
        case "INSERT", "UPDATE", "DELETE", "MERGE", "COMMIT", "ROLLBACK":
            return .dml(promise)
        case "CREATE", "ALTER", "DROP", "TRUNCATE":
            return .ddl(promise)
        default:
            throw OracleSQLError.malformedQuery(minified: sql)
        }

**Comment by lovetodream** [comment]
> Also, the flip side is that there doesn't seem to be a way to rollback

Yeah, this is my concern with adding a connection wide setting for auto commit.
There would be three ways to approach it, two of them not ideal imo.

## Approach 1

The first way is adding auto commit to `OracleConnection.Configuration`, this is not editable as long as the connection is alive. The only possibility to do rollbacks is by setting auto commit to false for every query you'd want to be able to rollback.

## Approach 2

Another way would be to add a `OracleConnection.autoCommit` property, which can be changed on the fly. But this might introduce undefined behavior if multiple queries are executed concurrently, e.g. for different requests in a web server. Let's consider something similar to this:

```swift
let connection: OracleConnection = ...
Task { 
    // we don't know when the task will be executed, it might be while
    // connection.autocommit is true
    do {
        try await connection.query("INSERT ...")
        try await connection.query("INSERT ...")
        try await connection.commit()
    } catch {
        try await connection.rollback() // this won't work if connection.autocommit is still true
    }
}
connection.autocommit = true
defer { connection.autocommit = false }
try await connection.query("UPDATE ...")
try await connection.query("UPDATE ...")
try await connection.query("UPDATE ...")
```

## Approach 3

Another hurdle is setting auto commit back to false after you done in approach 2, this might easly be forgotten. Similar to unlocking a lock.  
We could add something like `OracleConnection.withAutocommit<T: Result>(_ closure: (OracleConnection) async throws -> Result) async throws -> T` which handles auto commit internally and ensures it's always reset, and only used for the queries in the closure. This would be my favorite option. I don't know if that makes sense for the SQLKit usecase though, maybe you have some thoughts on it.

I think the downside of adding such a convieniance configuration (approach 1 and 2) might lead to more problems than it's worth.
Let me know what you think.


> I made a change that seems to work. I modified the switch statement (see below) in ExtendedQueryContext to add "COMMIT" as a .dlm and it seems to work. Rollback also seems to work.
> 
> ```
>     switch sqlKeyword {
>     case "DECLARE", "BEGIN", "CALL":
>         return .plsql(promise)
>     case "SELECT", "WITH":
>         return .query(promise)
>     case "INSERT", "UPDATE", "DELETE", "MERGE", "COMMIT", "ROLLBACK":
>         return .dml(promise)
>     case "CREATE", "ALTER", "DROP", "TRUNCATE":
>         return .ddl(promise)
>     default:
>         throw OracleSQLError.malformedQuery(minified: sql)
>     }
> ```

I don't think this is intended to work that way, but it might still be valid to investigate adding commit and rollback as working keywords, not as a dml though. The best solution might be to introduce a "unknown" category of some sort. And use that for everything other than the "registered" keywords. I'll check how other drivers handle this.

Until then, the only options you have is using either `QueryOptions.autocommit` or `OracleConnection.commit()` alongside `OracleConnection.rollback()` in case you need it.

I wonder why you didn't use that in the first place, are you unable to access these methods in the SQLKit wrapped db?

I'm looking forward to your ideas and thoughts on the matter :)

**Comment by fcobia** [comment]
Approach 1 is what I was thinking about. This is the way it was done with the MySQL JDBC adaptor if I remember correctly. You provided an auto commit parameter when making the database connection.

**Comment by lovetodream** [comment]
> > Until then, the only options you have is using either QueryOptions.autocommit or OracleConnection.commit() alongside OracleConnection.rollback() in case you need it.
> 
> I actually did not know those existed. I was simply trying to do it the same way I would do it in SQL the way I would do it on an interactive console.
> 
> The downside to this is that sql-kit does not support transactions. So, I would have to modify sql-kit to have commit and rollback on Database. However, it does support raw SQL which allows me to di it the way I did.

I just checked how first-party drivers do this. COMMIT and ROLLBACK can indeed be sent as a single commands. Although they do not qualify as DML. 

The best way to move on would be to add a fifth `Statement` case, which handles all keywords that don't fall into any of the above categories. The db server can handle invalid keywords instead of the client.

Do you want to submit a PR?

The things you'd have to do are
1. Adding the fifth category (maybe call it `plain`)
2. Writing a few tests to confirm commit and rollback work as expected.
3. (Optionally), add missing keywords for the existing statement types (see here: https://github.com/oracle/python-oracledb/blob/40d2b9789322ec0eefe43ccf6e86a25e98faf71b/src/oracledb/impl/thin/statement.pyx#L365-L378)

You shouldn't need to change anything on the binary messages, so it's a good first issue if you want to tackle it.

Please note, we shouldn't add explicit documentation for this, as using the dedicated `OracleConnection.commit()` and `OracleConnection.rollback()` methods is still the preferred method. Because the required bandwidth is a lot less, compared to the execute/query message. (See here: https://github.com/lovetodream/oracle-nio/blob/fa5dc481a582177ca1e30873e6cd9779a0df9c13/Sources/OracleNIO/Messages/Coding/OracleFrontendMessageEncoder.swift#L52-L65 compared to here: https://github.com/lovetodream/oracle-nio/blob/fa5dc481a582177ca1e30873e6cd9779a0df9c13/Sources/OracleNIO/Messages/Coding/OracleFrontendMessageEncoder.swift#L429-L605) It's also consistent with the first party python and js drivers, it's possible but not mentioned anywhere in the docs.

**Comment by lovetodream** [comment]
> Approach 1 is what I was thinking about. This is the way it was done with the MySQL JDBC adaptor if I remember correctly. You provided an auto commit parameter when making the database connection.

I'd like to keep this completely out of the driver for now, I'd prefer adding the ability for sending COMMIT and ROLLBACK first and see if that's enough. If it isn't enough, I'm always open to discuss it.

**Comment by fcobia** [comment]
I am slammed with work, but I appreciate you doing this, so I will try to take a look at it. 

I doubt it will be hard as it actually works as DML. I don’t actually know what DML stands for but that seemed to be the most appropriate place to put it. 

Good to know that the raw calls are faster/less overhead. I will switch my code to use those.

**Comment by lovetodream** [comment]
Awesome, just let me know if you don't have the time to work on it, it's no problem.

As soon as you have something implemented, feel free to open a PR and we can continue working on it together.

BTW, DML means something like data manipulation and stands for update, insert and delete. That's what I know at least, maybe I'm wrong.
